- name: roboshop instances management
  hosts: localhost
  become: true
  connection: localhost
  vars: 
    instances: ["mangodb", "redis", "mysql", "rabbitmq"]
    image_id: ami-0220d79f3f480ecf5
  tasks: 
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      instance_type: t3.micro
      name: "roboshop-{{ item }}"
      security_groups: 
      - "Testsc-{{ item }}" 
      - "Seg-Common"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print output
    debug:
      msg: "{{ ec2_output }}"
    
